<?php
$botSource = array(
"SeesaaBlog",
"Tumblr",
"Flickr",
"twitterfeed",
"gooBlog production",
"FC2 Blog Notify",
"livedoor Blog",
"ニコニコ生放送",
"ニコニコ動画",
"Intel Tweet City",
"twittbot.net",
"EasyBotter",
"MySweetBot",
"ツイッター bot",
"BotMaker",
"rakubo2",
"ツイート数カウントくん",
"リプライ数チェッカ",
"ツイ廃あらーと",
"Countter",
"paper.li",
"installNow",
"TweetMag1c for Android",
"Tweet Battery",
"＼( 'ω')／ウオオオオオアアアーーーッ！",
"占ぃったー",
"dlvr.it",
"twiroboJP",
"ツイ助。",
"TwitCasting",
"rekkacopy",
"なうぷれTunes",
"metabirds Botbird",
"makebot.sh",
"autotweety.net",
"Tweet Button",
"JOJO SS",
"Colotwi",
"find_keyword_api_dev5",
"foods_foods_",
"Ameba smartphone",
"Ameba_Blog",
"Ustream.TV",
"twimaker",
"このまま眠りつづけて死ぬ",
"Friend Ranking",
"ヘブンネット",
"なるほどえたきちじゃねーの",
"バードアタッカー.com",
"WordPress.com",
"ぐへへ～(＾p＾)",
"最新ニュース.jp",
"The Tribez for iPad",
"The Tribez on iOS",
"黒歴史クリーナー",
"IFTTT",
"TW_NEWSYSTEM_API0003",
"ツイッターニュース限定版",
"buleBird for Iphone",
"YasuakiHiguchi115511",
"今日、誰と一緒に食べる？",
"TweetAdder v4",
"TweetMag1c MusicEdition",

);
?>